name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"     # Runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk/svg-only@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: "nithyarajmudhaliyar"

      - name: Push Snake Animation
        uses: EndBug/add-and-commit@v9
        with:
          add: "github-contribution-grid-snake.svg"
          message: "Generated Snake Animation"
